feat: change file for exists share
stonith404/pingvin-share pull request #306
Opened 2023-11-01 16:27 UTC by IvanLi-CN

close #154 。

This is the effect achieved. Is there anything that needs to be adjusted in the process?

https://github.com/stonith404/pingvin-share/assets/30215105/08773c4c-12ab-4360-83fd-5c7f45de81a4

2023-11-02 07:14 UTC, stonith404 commented
Thanks! I'll look into it at the weekend.

2023-11-03 13:20 UTC, stonith404 commented on backend/src/file/file.service.ts
> +    return {
I think the return value of this function isn't used anywhere so we could make the function void

2023-11-03 13:23 UTC, stonith404 commented on backend/src/share/guard/shareOwner.guard.ts
> +    if (!await super.canActivate(context)) return false;
That's a good addition, thanks :)

2023-11-03 13:28 UTC, stonith404 commented on backend/src/share/share.controller.ts
> +  @UseGuards(JwtGuard, ShareOwnerGuard)
We can remove `JwtGuard` here because `ShareOwnerGuard` extends it now
```suggestion
  @UseGuards(ShareOwnerGuard)
```

2023-11-03 13:33 UTC, stonith404 commented on frontend/src/components/upload/FileList.tsx
> +              color="blue"
```suggestion
              color="primary"
```
I prefer the primary Pingvin Share color but let me know if you don't agree.

2023-11-03 13:34 UTC, stonith404 commented on frontend/src/pages/account/shares.tsx
> +                      <Link href={`/share/${share.id}/edit`}>
Could you move the edit icon directly to the left of the delete icon?

2023-11-03 13:38 UTC, stonith404 requested changes
Sorry for being so picky, but these should be only small changes. I really like the implementation of the feature. Thank you! :)

2023-11-03 21:04 UTC, stonith404 commented
@IvanLi-CN, for me, it doesn't really matter. Do what you think is best. If you ask for my opinion, I would suggest redirecting back to the "My Shares" page, as that is the page the user is coming from.

2023-11-04 03:05 UTC, IvanLi-CN commented
Modified, please check 😋  @stonith404

2023-11-04 14:00 UTC, stonith404 approved these changes
Great, thank you! Can I merge?

2023-11-04 16:55 UTC, IvanLi-CN commented
> Great, thank you! Can I merge?

Do it! 😋

2023-11-04 19:39 UTC, merged

2023-11-04 21:09 UTC, pierrbt commented
Wow nice changes, good job !