README.es.md
stonith404/pingvin-share pull request #356
Opened 2023-12-12 21:58 UTC by NoSoloHacking

Replaced the review for the Spanish version with No Solo Hacking's review of the tool.

2023-12-13 07:41 UTC, stonith404 requested changes

2023-12-13 07:41 UTC, stonith404 commented on docs/README.es.md
> +- [Reseña realizada por No Solo Hacking](https://www.youtube.com/watch?v=ocd4EpLTYkU)
```suggestion
- [Reseña realizada por No Solo Hacking (español)](https://www.youtube.com/watch?v=ocd4EpLTYkU)
- [Reseña por DB Tech (inglés)](https://www.youtube.com/watch?v=rWwNeZCOPJA)
```

Great thanks for your video :) I would keep the review of DB Tech in the README but add a note that this review is on English. Above is my suggestion but I'm not sure if it is grammatically correct.

2023-12-14 21:57 UTC, NoSoloHacking commented
It's correct as you suggested it.

2023-12-15 06:26 UTC, stonith404 approved these changes

2023-12-15 06:27 UTC, merged