add(discord restriction id): this pull has one QOL add and a discord oauth id restriction
stonith404/pingvin-share pull request #621
Opened 2024-09-27 20:06 UTC by COMPLEXWASTAKEN

hello. I have added a discord oauth id restriction to where you can set a set of ids like <id>,<id> and if there id is not there it will not allow them to register with discord oauth

lmk if you want anything changed or find bugs

2024-09-29 18:37 UTC, stonith404 requested changes
Thanks for your contribution :) 

The code looks good to me but could you please remove all translations and only keep the changes for the `en-US.ts` file. The strings will get translated by contributors on Crowdin.

2024-09-29 18:37 UTC, stonith404 commented on backend/src/oauth/provider/discord.provider.ts
> +    const limitedusers = this.config.get("oauth.discord-limitedUsers");
Sorry for being so picky but could you please rename the variable to `limitedUsers`?
```suggestion
    const limitedUsers = this.config.get("oauth.discord-limitedUsers");
```

2024-09-29 19:04 UTC, COMPLEXWASTAKEN commented
oops i didnt mean to push the other to this pull request

2024-09-29 21:04 UTC, stonith404 commented
No problem, but could you please remove these changes from this PR? After that it should be ready to merge :)

Regarding the email restriction, I think this would need a bit more discussion as I've mentioned, the feature doesn't really make sense for email and password authentication.

2024-09-29 21:05 UTC, COMPLEXWASTAKEN commented
How do I remove them I have never did a pull request on GitHub lol

2024-09-29 21:15 UTC, stonith404 commented
You have to do this in the Git CLI locally with the command `git revert <commit-that-you-want-to-revert>`. In this case it would be `git revert 91fb162558cffd5f8685f1eb606729874ff640db`. After that you can normally run `git push` and the commit should be reverted :)

2024-09-29 21:50 UTC, COMPLEXWASTAKEN commented
done

2024-09-30 06:52 UTC, stonith404 approved these changes

2024-09-30 06:53 UTC, merged