feat: Show QR code for share in information and creation modal
stonith404/pingvin-share pull request #723
Opened 2024-12-30 03:48 UTC by aarondoet

closes #244 

![example](https://github.com/user-attachments/assets/2dc0e2a8-7afd-4640-b508-6eab5464ecdc)

2024-12-31 10:25 UTC, stonith404 commented
That's a nice addition, thanks. In my opinion it would be nice if the admin could enable or disable if QR codes should be shown. What do you think?

2024-12-31 10:36 UTC, aarondoet commented
I'd say this would rather be personal settings, not something the admin needs to set for everyone.

2024-12-31 12:40 UTC, stonith404 commented
Yeah you're right, that makes more sense.

2025-01-14 09:12 UTC, stonith404 requested changes
I thought about the user option but in my opinion it would make more sense to add a button next to the copy link button that shows the QR code when clicked.

2025-04-05 10:40 UTC, Halogly commented
Hello author, may I ask if there is a merge feature in the new version? I discovered that this feature is not available after I deployed it with Docker.

2025-04-05 18:29 UTC, aarondoet commented
This PR has not yet been merged because of requested changes. However I currently do not have the time to work on it.

2026-01-14 09:39 UTC, closed without merging